# NUC NAS Hub - Smart Content Generator V2
# Features: Duplicate Detection + SEO Optimization + Smart Category

param(
    [int]$Count = 3,
    [string]$Category = "",
    [switch]$Publish
)

$ErrorActionPreference = "Stop"

$RepoDir = "D:\Projects\nucnas-hub"
$ContentDir = "$RepoDir\content"

$secrets = Get-Content "$RepoDir\secrets.json" -Encoding UTF8 | ConvertFrom-Json
$PexelsToken = $secrets.pexels_token

$categoryMap = @{
    "hardware" = "hardware"
    "apple" = "hardware"
    "intel" = "hardware"
    "amd" = "hardware"
    "workstation" = "hardware"
    "nas" = "nas"
    "ai" = "ai"
}

function Get-PexelsImage {
    param([string]$Query)
    
    if (-not $PexelsToken) {
        return @{ url = "https://images.pexels.com/photos/1148820/pexels-photo-1148820.jpeg"; credit = "Pexels" }
    }
    
    try {
        $url = "https://api.pexels.com/v1/search?query=$([uri]::EscapeDataString($Query))&per_page=1"
        $response = Invoke-RestMethod -Uri $url -Headers @{"Authorization" = $PexelsToken} -Method Get -TimeoutSec 10
        if ($response.photos -and $response.photos.Count -gt 0) {
            return @{ url = $response.photos[0].src.large2x; credit = $response.photos[0].photographer }
        }
    } catch {
        Write-Host "[WARN] Pexels: $_"
    }
    return @{ url = "https://images.pexels.com/photos/1148820/pexels-photo-1148820.jpeg"; credit = "Pexels" }
}

function Get-Slug {
    param([string]$Title)
    $slug = $Title.ToLower()
    $slug = $slug -replace '[^\w\s-]', ''
    $slug = $slug -replace '\s+', '-'
    $slug = $slug -replace '-+', '-'
    return $slug.Trim('-')
}

function Test-Duplicate {
    param([string]$Title, [string]$Category)
    
    $slug = Get-Slug -Title $Title
    $possiblePaths = @(
        "$ContentDir\$Category\$slug.md",
        "$ContentDir\hardware\$slug.md",
        "$ContentDir\nas\$slug.md",
        "$ContentDir\ai\$slug.md"
    )
    
    foreach ($path in $possiblePaths) {
        if (Test-Path $path) { return $true }
    }
    return $false
}

function Get-ArticleCategory {
    param([string]$Type)
    $typeLower = $Type.ToLower()
    if ($categoryMap.ContainsKey($typeLower)) { return $categoryMap[$typeLower] }
    return "hardware"
}

function New-Article {
    param(
        [string]$Title,
        [string]$Category,
        [string]$Summary,
        [string[]]$Keywords
    )
    
    $date = Get-Date -Format "yyyy-MM-dd"
    $slug = Get-Slug -Title $Title
    $filename = "$ContentDir\$Category\$slug.md"
    
    if (Test-Duplicate -Title $Title -Category $Category) {
        return @{ status = "skipped"; reason = "duplicate"; title = $Title }
    }
    
    $image = Get-PexelsImage -Query $Title
    $imageUrl = $image.url
    $photographer = $image.credit
    
    $tags = @()
    if ($Keywords) {
        $tags += $Keywords[0..([Math]::Min(2, $Keywords.Count-1))]
    }
    $tags += $Category
    $tagsStr = ($tags | ForEach-Object { "`"$_`"" }) -join ", "
    
    $content = @"
---
title: "$Title"
date: $date
summary: "$Summary"
description: "$Summary"
categories: ["$Category"]
tags: [$tagsStr]
keywords: [$tagsStr]
image: "$imageUrl"
imageCredit: "$photographer"
---

# $Title

![]($imageUrl)

## Overview

$Summary

## Key Features

- High-performance processor
- Compact design
- Rich connectivity
- Excellent cooling

## Use Cases

- Home office
- Light gaming
- Media entertainment
- Professional work

## Conclusion

$Title is a recommended $Category device with excellent design and performance.

---
*Auto-generated by NUC NAS Hub*
"@
    
    $dir = Split-Path $filename -Parent
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }
    
    Set-Content -Path $filename -Value $content -Encoding UTF8
    return @{ status = "created"; title = $Title; category = $Category; slug = $slug }
}

Write-Host "========================================"
Write-Host "  NUC NAS Hub Content Generator V2"
Write-Host "========================================"

$planFile = "$RepoDir\content_plan.json"
$pending = @()
if (Test-Path $planFile) {
    $plan = Get-Content $planFile -Encoding UTF8 | ConvertFrom-Json
    $pending = $plan | Where-Object { $_.status -eq "pending" }
    Write-Host "[INFO] Pending: $($pending.Count) articles"
}

$generated = 0
$skipped = 0

foreach ($i in 0..($Count-1)) {
    if ($pending.Count -eq 0) {
        Write-Host "[INFO] No more pending articles!"
        break
    }
    
    $item = $pending[$i % $pending.Count]
    $targetCategory = Get-ArticleCategory -Type $item.type
    if ($Category) { $targetCategory = $Category }
    
    $title = "$($item.brand) $($item.model)"
    $summary = "$($item.brand) $($item.model): $($item.keywords)"
    $keywords = $item.keywords -split ','
    
    Write-Host ""
    Write-Host "[PROCESS] $title ($targetCategory)"
    
    $result = New-Article -Title $title -Category $targetCategory -Summary $summary -Keywords $keywords
    
    if ($result.status -eq "created") {
        Write-Host "[OK] Created: $($result.slug)" -ForegroundColor Green
        $generated++
    } else {
        Write-Host "[SKIP] Reason: $($result.reason)" -ForegroundColor Yellow
        $skipped++
    }
}

Write-Host ""
Write-Host "========================================"
Write-Host "[DONE] Created=$generated | Skipped=$skipped"
Write-Host "========================================"

if ($Publish -and $generated -gt 0) {
    Write-Host ""
    Write-Host "[BUILD] Building and publishing..."
    Set-Location $RepoDir
    hugo
    git add -A
    git commit -m "Auto publish $(Get-Date -Format 'yyyy-MM-dd HH:mm')"
    git push
    Write-Host "[DONE] Published!" -ForegroundColor Green
}
