#!/usr/bin/env python3
# NUC NAS Hub - Content Generator V3 with MiniMax AI

import json
import os
import re
import subprocess
import requests
from datetime import datetime

CONFIG = {
    "repo_dir": r"D:\Projects\nucnas-hub",
    "content_dir": r"D:\Projects\nucnas-hub\content",
    "secrets_file": r"D:\Projects\nucnas-hub\secrets.json",
    "plan_file": r"D:\Projects\nucnas-hub\content_plan.json"
}

CATEGORY_MAP = {
    "hardware": "hardware", "apple": "hardware", "intel": "hardware",
    "amd": "hardware", "workstation": "hardware", "nas": "nas", "ai": "ai"
}

def load_config():
    with open(CONFIG["secrets_file"], "r", encoding="utf-8") as f:
        secrets = json.load(f)
    return secrets.get("pexels_token", ""), secrets.get("minimax_token", "")

def get_ai_content(brand, model, keywords, category, token):
    if not token:
        return None
    
    prompt = f"""你是一个专业的科技评测编辑。请为以下产品写一篇评测文章：

产品: {brand} {model}
特点: {keywords}
分类: {category}

请用中文写一篇300-500字的评测文章，包括：
1. 产品简介（一句话）
2. 主要特点（3-5点）
3. 适用场景
4. 总结评价

直接输出文章内容，不要有其他格式或前缀。"""

    url = "https://api.minimax.chat/v1/text/chatcompletion_pro"
    headers = {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}
    body = {
        "model": "abab6.5s-chat",
        "messages": [{"role": "user", "content": prompt}]
    }
    
    try:
        print("[AI] Generating content...")
        resp = requests.post(url, headers=headers, json=body, timeout=60)
        data = resp.json()
        if "choices" in data and len(data["choices"]) > 0:
            return data["choices"][0]["message"]["content"]
    except Exception as e:
        print(f"[ERROR] AI: {e}")
    return None

def get_pexels_image(query, token):
    default_url = "https://images.pexels.com/photos/1148820/pexels-photo-1148820.jpeg"
    if not token:
        return default_url, "Pexels"
    
    try:
        url = f"https://api.pexels.com/v1/search?query={requests.utils.quote(query)}&per_page=1"
        resp = requests.get(url, headers={"Authorization": token}, timeout=10)
        data = resp.json()
        if "photos" in data and len(data["photos"]) > 0:
            return data["photos"][0]["src"]["large2x"], data["photos"][0]["photographer"]
    except Exception as e:
        print(f"[WARN] Pexels: {e}")
    return default_url, "Pexels"

def get_slug(title):
    slug = title.lower()
    slug = re.sub(r'[^\w\s-]', '', slug)
    slug = re.sub(r'\s+', '-', slug)
    slug = re.sub(r'-+', '-', slug)
    return slug.strip('-')

def check_duplicate(title, category):
    slug = get_slug(title)
    paths = [
        f"{CONFIG['content_dir']}\\{category}\\{slug}.md",
        f"{CONFIG['content_dir']}\\hardware\\{slug}.md",
        f"{CONFIG['content_dir']}\\nas\\{slug}.md",
        f"{CONFIG['content_dir']}\\ai\\{slug}.md"
    ]
    return any(os.path.exists(p) for p in paths)

def get_category(type_):
    return CATEGORY_MAP.get(type_.lower(), "hardware")

def create_article(brand, model, keywords, category, pexels_token, minimax_token):
    title = f"{brand} {model}"
    date = datetime.now().strftime("%Y-%m-%d")
    slug = get_slug(title)
    filename = f"{CONFIG['content_dir']}\\{category}\\{slug}.md"
    
    if check_duplicate(title, category):
        return {"status": "skipped", "reason": "duplicate", "title": title}
    
    # Get AI content
    ai_content = get_ai_content(brand, model, keywords, category, minimax_token)
    
    # Get image
    image_url, photographer = get_pexels_image(title, pexels_token)
    
    summary = f"{brand} {model} review: {keywords}"
    tags = f'"{brand}", "{model}", "{category}"'
    
    if ai_content:
        body = ai_content
    else:
        body = f"""## {title}

{summary}

### Product Overview

{title} is a notable product in its category.

### Key Features

- High-performance processor
- Compact design
- Rich connectivity options
- Excellent cooling system

### Use Cases

- Home office
- Entertainment
- Light gaming

### Conclusion

{title} is a recommended choice with excellent design and performance."""

    content = f"""---
title: "{title}"
date: {date}
summary: "{summary}"
description: "{summary}"
categories: ["{category}"]
tags: [{tags}]
keywords: "{keywords}"
image: "{image_url}"
imageCredit: "{photographer}"
---

# {title}

![]({image_url})

{body}

---
*Auto-generated by NUC NAS Hub*
"""
    
    os.makedirs(os.path.dirname(filename), exist_ok=True)
    with open(filename, "w", encoding="utf-8") as f:
        f.write(content)
    
    return {"status": "created", "title": title, "category": category, "slug": slug}

def main():
    import sys
    count = 3
    category = ""
    publish = False
    
    for arg in sys.argv[1:]:
        if arg.startswith("-Count="):
            count = int(arg.split("=")[1])
        elif arg.startswith("-Category="):
            category = arg.split("=")[1]
        elif arg == "-Publish":
            publish = True
    
    print("=" * 40)
    print("  NUC NAS Hub Content Generator V3")
    print("  [AI: MiniMax Connected]")
    print("=" * 40)
    
    pexels_token, minimax_token = load_config()
    
    # Load plan
    with open(CONFIG["plan_file"], "r", encoding="utf-8") as f:
        plan = json.load(f)
    
    pending = [p for p in plan if p.get("status") == "pending"]
    print(f"[INFO] Pending: {len(pending)} articles")
    
    generated = 0
    skipped = 0
    
    for i in range(count):
        if not pending:
            print("[INFO] No more pending articles!")
            break
        
        item = pending[i % len(pending)]
        target_category = get_category(item.get("type", "hardware"))
        if category:
            target_category = category
        
        print(f"\n[PROCESS] {item['brand']} {item['model']} ({target_category})")
        
        result = create_article(
            item['brand'], item['model'], item['keywords'],
            target_category, pexels_token, minimax_token
        )
        
        if result["status"] == "created":
            print(f"[OK] Created: {result['slug']}")
            generated += 1
        else:
            print(f"[SKIP] {result['reason']}")
            skipped += 1
    
    print("\n" + "=" * 40)
    print(f"[DONE] Created={generated} | Skipped={skipped}")
    print("=" * 40)
    
    if publish and generated > 0:
        print("\n[BUILD] Publishing...")
        os.chdir(CONFIG["repo_dir"])
        subprocess.run(["hugo"], capture_output=True)
        subprocess.run(["git", "add", "-A"], capture_output=True)
        subprocess.run(["git", "commit", "-m", f"Auto {datetime.now().strftime('%Y-%m-%d %H:%M')}"], capture_output=True)
        subprocess.run(["git", "push"], capture_output=True)
        print("[DONE] Published!")

if __name__ == "__main__":
    main()
