# NUC NAS Hub - Content Generator Script
# Usage: .\generate.ps1 -Count 3

param(
    [int]$Count = 3,
    [string]$Category = "",
    [switch]$Publish
)

$ErrorActionPreference = "Stop"

$RepoDir = "D:\Projects\nucnas-hub"
$ContentDir = "$RepoDir\content"

# Read config
$secrets = Get-Content "$RepoDir\secrets.json" -Encoding UTF8 | ConvertFrom-Json
$PexelsToken = $secrets.pexels_token

# Category mapping based on type
$categoryMap = @{
    "hardware" = "hardware"
    "apple" = "hardware"
    "intel" = "hardware"
    "amd" = "hardware"
    "workstation" = "hardware"
    "nas" = "nas"
    "ai" = "ai"
}

function Get-PexelsImage {
    param([string]$Query)
    
    if (-not $PexelsToken) {
        return @{
            url = "https://images.pexels.com/photos/1148820/pexels-photo-1148820.jpeg"
            credit = "Pexels"
        }
    }
    
    $url = "https://api.pexels.com/v1/search?query=$([uri]::EscapeDataString($Query))&per_page=1"
    $headers = @{
        "Authorization" = $PexelsToken
    }
    
    try {
        $response = Invoke-RestMethod -Uri $url -Headers $headers -Method Get -TimeoutSec 10
        if ($response.photos -and $response.photos.Count -gt 0) {
            $photo = $response.photos[0]
            return @{
                url = $photo.src.large2x
                credit = $photo.photographer
            }
        }
    } catch {
        Write-Host "Pexels API Error: $_"
    }
    
    return @{
        url = "https://images.pexels.com/photos/1148820/pexels-photo-1148820.jpeg"
        credit = "Pexels"
    }
}

function Get-Slug {
    param([string]$Title)
    $slug = $Title -replace '[^\w]', '-' -replace '-+', '-'
    return $slug.ToLower()
}

function Test-Duplicate {
    param([string]$Filename)
    return Test-Path $filename
}

function Get-ArticleCategory {
    param([string]$Type)
    $typeLower = $Type.ToLower()
    if ($categoryMap.ContainsKey($typeLower)) {
        return $categoryMap[$typeLower]
    }
    # Default to hardware for review products
    return "hardware"
}

function New-Article {
    param(
        [string]$Title,
        [string]$Category,
        [string]$Summary,
        [string[]]$Tags
    )
    
    $date = Get-Date -Format "yyyy-MM-dd"
    $slug = Get-Slug -Title $Title
    $filename = "$ContentDir\$Category\$slug.md"
    
    # Check for duplicate
    if (Test-Duplicate -Filename $filename) {
        Write-Host "SKIP (duplicate): $filename"
        return $null
    }
    
    # Get image
    $image = Get-PexelsImage -Query $Title
    $imageUrl = $image.url
    $photographer = $image.credit
    
    # Format tags
    $tagsStr = ($Tags | ForEach-Object { "`"$_`"" }) -join ", "
    
    $content = @"
---
title: "$Title"
date: $date
summary: "$Summary"
categories: ["$Category"]
tags: [$tagsStr]
image: "$imageUrl"
imageCredit: "$photographer"
---

# $Title

![]($imageUrl)

$Summary

---
*Auto-generated by NUC NAS Hub*
"@
    
    # Ensure directory exists
    $dir = Split-Path $filename -Parent
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }
    
    Set-Content -Path $filename -Value $content -Encoding UTF8
    Write-Host "Created: $filename"
    return $filename
}

# Main
Write-Host "========================================"
Write-Host "  NUC NAS Hub Content Generator"
Write-Host "========================================"
Write-Host ""

# Read content plan
$planFile = "$RepoDir\content_plan.json"
$pending = @()
if (Test-Path $planFile) {
    $plan = Get-Content $planFile -Encoding UTF8 | ConvertFrom-Json
    $pending = $plan | Where-Object { $_.status -eq "pending" }
    Write-Host "Pending articles: $($pending.Count)"
    Write-Host ""
}

# Generate articles
$generated = 0
$skipped = 0

foreach ($i in 0..($Count-1)) {
    if ($pending.Count -eq 0) {
        Write-Host "No more pending articles!"
        break
    }
    
    $item = $pending[$i % $pending.Count]
    
    # Determine correct category based on type
    $targetCategory = Get-ArticleCategory -Type $item.type
    
    # Override if user specified category
    if ($Category) {
        $targetCategory = $Category
    }
    
    $title = "$($item.brand) $($item.model)"
    $summary = "$($item.brand) $($item.model) review: $($item.keywords)"
    $tags = @($item.brand, $item.model, $item.type)
    
    $result = New-Article -Title $title -Category $targetCategory -Summary $summary -Tags $tags
    
    if ($result) {
        $generated++
    } else {
        $skipped++
    }
}

Write-Host ""
Write-Host "Generated: $generated | Skipped: $skipped"
Write-Host ""

if ($Publish -and $generated -gt 0) {
    Write-Host "Building and publishing..."
    Set-Location $RepoDir
    hugo
    git add -A
    git commit -m "Auto publish $(Get-Date -Format 'yyyy-MM-dd HH:mm')"
    git push
    Write-Host "Done!"
}
