# NUC NAS Hub - Content Generator V3
param([int]$Count=3,[string]$Category="",[switch]$Publish)
$ErrorActionPreference="Stop";$RepoDir="D:\Projects\nucnas-hub";$ContentDir="$RepoDir\content"
$secrets=Get-Content "$RepoDir\secrets.json"|ConvertFrom-Json;$PexelsToken=$secrets.pexels_token;$MiniMaxToken=$secrets.minimax_token
$categoryMap=@{"hardware"="hardware";"apple"="hardware";"intel"="hardware";"amd"="hardware";"workstation"="hardware";"nas"="nas";"ai"="ai"}
function Get-AIContent{param($Brand,$Model,$Keywords,$Category)
if(-not $MiniMaxToken){return $null}
$prompt="Write a 300-500 word product review in Chinese for: $Brand $Model. Features: $Keywords. Include: intro, features, usecases, conclusion."
$url="https://api.minimax.chat/v1/text/chatcompletion_pro";$headers=@{"Authorization"="Bearer $MiniMaxToken";"Content-Type"="application/json"}
$body=@{model="abab6.5s-chat";messages=@(@{role="user";content=$prompt})}|ConvertTo-Json -Depth 3
try{Write-Host "[AI] Generating...";$response=Invoke-RestMethod -Uri $url -Headers $headers -Method Post -Body $body -TimeoutSec 60
if($response.choices -and $response.choices[0].message){return $response.choices[0].message.content}}catch{Write-Host "[ERROR] AI: $_"}
return $null}
function Get-PexelsImage{param($Query)
if(-not $PexelsToken){return @{url="https://images.pexels.com/photos/1148820/pexels-photo-1148820.jpeg";credit="Pexels"}}
try{$url="https://api.pexels.com/v1/search?query=$([uri]::EscapeDataString($Query))&per_page=1";$response=Invoke-RestMethod -Uri $url -Headers @{"Authorization"=$PexelsToken} -Method Get -TimeoutSec 10
if($response.photos -and $response.photos.Count-gt 0){return @{url=$response.photos[0].src.large2x;credit=$response.photos[0].photographer}}}catch{}
return @{url="https://images.pexels.com/photos/1148820/pexels-photo-1148820.jpeg";credit="Pexels"}}
function Get-Slug{param($Title);$slug=$Title.ToLower()-replace'[^\w\s-]',''-replace'\s+','-' -replace'-+','-';return $slug.Trim('-')}
function Test-Duplicate{param($Title,$Category);$slug=Get-Slug -Title $Title;$paths=@("$ContentDir\$Category\$slug.md","$ContentDir\hardware\$slug.md","$ContentDir\nas\$slug.md","$ContentDir\ai\$slug.md");foreach($p in $paths){if(Test-Path $p){return $true}};return $false}
function Get-ArticleCategory{param($Type);$t=$Type.ToLower();if($categoryMap.ContainsKey($t)){return $categoryMap[$t]};return "hardware"}
function New-Article{param($Brand,$Model,$Keywords,$Category)
$title="$Brand $Model";$date=Get-Date -Format "yyyy-MM-dd";$slug=Get-Slug -Title $title;$filename="$ContentDir\$Category\$slug.md"
if(Test-Duplicate -Title $title -Category $Category){return @{status="skipped";reason="duplicate";title=$title}}
$aiContent=Get-AIContent -Brand $Brand -Model $Model -Keywords $Keywords -Category $Category
$image=Get-PexelsImage -Query $title;$imageUrl=$image.url;$photographer=$image.credit;$summary="$Brand $Model review: $Keywords"
$tags=@($Brand,$Model,$Category);$tagsStr=($tags|ForEach-Object{"`"$_`""}) -join", "
if($aiContent){$bodyContent=$aiContent}else{$bodyContent="## $title`n`n$summary`n`n### Features`n- High performance`n- Compact design`n- Rich connectivity`n`n### Use Cases`n- Home office`n- Entertainment`n`n### Conclusion`n$title is recommended."}
$content="---\ntitle: `"$title`"\ndate: $date\nsummary: `"$summary`"\ndescription: `"$summary`"\ncategories: [`"$Category`"]\ntags: [$tagsStr]\nkeywords: `"$Keywords`"\nimage: `"$imageUrl`"\nimageCredit: `"$photographer`"\n---\n`n# $title`n`n![]($imageUrl)`n`n$bodyContent`n`n---\n*Auto-generated by NUC NAS Hub*\n"
$dir=Split-Path $filename-Parent;if(-not(Test-Path $dir)){New-Item -ItemType Directory -Path $dir-Force|Out-Null}
Set-Content -Path $filename -Value $content -Encoding UTF8;return @{status="created";title=$title;category=$Category;slug=$slug}}
Write-Host "========================================" -ForegroundColor Cyan;Write-Host "  NUC NAS Hub Content Generator V3" -ForegroundColor Cyan;Write-Host "  [AI: MiniMax Connected]" -ForegroundColor Cyan;Write-Host "========================================" -ForegroundColor Cyan
$planFile="$RepoDir\content_plan.json";$pending=@()
if(Test-Path $planFile){$plan=Get-Content $planFile -Encoding UTF8|ConvertFrom-Json;$pending=$plan|Where-Object{$_.status -eq"pending"};Write-Host "[INFO] Pending: $($pending.Count) articles"}
$generated=0;$skipped=0
foreach($i in 0..($Count-1)){if($pending.Count-eq 0){Write-Host "[INFO] No more pending!";break}
$item=$pending[$i%$pending.Count];$targetCategory=Get-ArticleCategory -Type $item.type;if($Category){$targetCategory=$Category}
Write-Host "";Write-Host "[PROCESS] $($item.brand) $($item.model) ($targetCategory)"
$result=New-Article -Brand $item.brand -Model $item.model -Keywords $item.keywords -Category $targetCategory
if($result.status -eq"created"){Write-Host "[OK] Created: $($result.slug)" -ForegroundColor Green;$generated++}else{Write-Host "[SKIP] $($result.reason)" -ForegroundColor Yellow;$skipped++}}
Write-Host "";"========================================";"[DONE] Created=$generated | Skipped=$skipped";"========================================"
if($Publish -and $generated-gt 0){Write-Host "";"[BUILD] Publishing...";Set-Location $RepoDir;hugo;git add -A;git commit -m "Auto $(Get-Date -Format 'yyyy-MM-dd HH:mm')";git push;"[DONE] Published!" -ForegroundColor Green}